server:
  port: 8085
  
# 文件上传路径配置
file:
  upload-dir: ./uploads

spring:
  profiles:
    active: database
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  # 配置文件上传目录
  web:
    resources:
      static-locations: classpath:/static/,file:${file.upload-dir}
  # 解决Springfox与Spring Boot 2.7.0的兼容性问题
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

# Knife4j配置
knife4j:
  enable: true
  setting:
    language: zh-CN
    enableSwaggerModels: true
    enableDocumentManage: true
    swaggerModelName: 实体类列表
    enableSearch: true
    enableOpenApi: false
    enableAfterScript: true
    enableFilterMultipartApiMethodType: POST
    enableHomeCustom: true
    homeCustomLocation: classpath:knife4j/home.md

jwt:
  secret: thfh-admin-secret-key
  expiration: 86400 

# 菜鸟驿站API配置
cainiao:
  api:
    url: https://api.cainiao.com/logistics/track
    key: your_api_key_here
