server:
  port: 8085
  host: 8.138.226.198
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false
  
# 文件上传路径配置
file:
  upload-dir: ./uploads

spring:
  profiles:
    active: database
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      # 临时文件清理配置
      file-size-threshold: 2MB  # 超过2MB的文件会被写入临时目录
      location: ./temp      # 临时文件存储目录
  
  # 配置文件上传目录
  web:
    resources:
      static-locations: classpath:/static/,file:${file.upload-dir}
      add-mappings: false  # 禁用资源映射，保证404能被异常处理器捕获
  mvc:
    throw-exception-if-no-handler-found: true  # 启用404异常处理
      
  # 配置Tomcat临时目录
  tomcat:
    basedir: ./temp

# Knife4j配置 (OpenAPI 3)
knife4j:
  enable: true
  setting:
    language: zh-CN
    enable-swagger-models: true
    enable-document-manage: true
    swagger-model-name: 实体类列表
    enable-search: true
    enable-open-api: false
    enable-after-script: true
    enable-filter-multipart-api-method-type: POST
    enable-home-custom: true
    home-custom-location: classpath:knife4j/home.md
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

jwt:
  secret: thfh-admin-secret-key
  expiration: 3600  # 1小时
  refreshExpiration: 2592000  # 30天

# 菜鸟驿站API配置
cainiao:
  api:
    url: https://api.cainiao.com/logistics/track
    key: your_api_key_here

# 全局日志配置
logging:
  level:
    root: INFO
    com.thfh: INFO
    org.springframework: WARN

# 推荐系统配置
recommendation:
  data:
    path: ./recommendation-data
  rebuild:
    interval: 48  # 每48小时重建一次推荐模型
